

HAL_GPIO_WritePin(GPIOA, GPIO_PIN_12, GPIO_PIN_SET);//LED1
HAL_GPIO_WritePin(GPIOA, GPIO_PIN_11, GPIO_PIN_SET);//LED2
HAL_GPIO_WritePin(GPIOA, GPIO_PIN_10, GPIO_PIN_SET);//LED3


HAL_GPIO_WritePin(GPIOB, GPIO_PIN_5, GPIO_PIN_SET);//R_1-2
HAL_GPIO_WritePin(GPIOA, GPIO_PIN_15, GPIO_PIN_SET);//G_1-3
HAL_GPIO_WritePin(GPIOB, GPIO_PIN_4, GPIO_PIN_SET);//B_1-4

HAL_GPIO_WritePin(GPIOB, GPIO_PIN_14, GPIO_PIN_SET);//R_2-2
HAL_GPIO_WritePin(GPIOB, GPIO_PIN_12, GPIO_PIN_SET);//G_2-3
HAL_GPIO_WritePin(GPIOB, GPIO_PIN_13, GPIO_PIN_SET);//B_2-4



